version: '3.8'

services:
  # Наш Node.js сервер
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      # ЗВЕРНИ УВАГУ: тут ми підключаємось не до localhost чи Atlas, а до контейнера "mongodb"
      - MONGO_URI=mongodb://mongodb:27017/designstudio
      - JWT_SECRET=super_secret_key_12345
      - PORT=3000
      - EMAIL_USER=kozakmarian06@gmail.com
      - EMAIL_PASS=puoqdktzbjxehdlu
    depends_on:
      - mongodb

  # База даних MongoDB
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
